version: "3.8"

services:

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - capteur-net

  capteur-service:
    build: .
    container_name: capteur-service
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/mon_capteur_db
    networks:
      - capteur-net

volumes:
  mongodb_data:

networks:
  capteur-net:
