@@startuml senario_activation_orchestateur


collections WS_orchestrateur as wso
collections WS_capteur as wsc
participant Esp32 as esp
boundary dispplay as di

group update deviceDB 
    wso -> wsc : get all capteurs
    wsc -> wso : capteur_list 
    loop capteurs in capteur_list
        alt if capteur refer to a new device
            wsc -> wsc : append new device in DB
        end
    end
end

loop for device in devices
    loop for constrainte in device.constraint
        wso -> wsc : get capteur value
        wsc -> wso : value 
        alt value is not in threshold 
            wso -> esp : change display status (lcd / led)
            esp -> di : change display value/status
        end
    end
end



@@enduml