@@startuml senario_activation_orchestateur


collections WS_orchestrateur as wso
collections WS_capteur as wsc
participant Esp8266 as esp
boundary display as di
boundary led as led

group update device & apply Constraint
    wso -> wsc : get all capteurs
    wsc -> wso : capteur_list 
    loop capteur in capteur_list
        alt capteur not register in device's capteurs
            wso -> wso : append new capteurs in Device
        end

        alt capteur type is lum & value < lum_threshold
            wso -> esp : request activate led
            esp -> led : activate led
        else capteur type is lum & value > lum_threshold
            wso -> esp : request deactivate led 
            esp -> led : deactivate led
        end

        alt capteur type is humid & value < humid_threshold
            wso -> esp : request display "vmc low speed"
            esp -> di : update display content
        else capteur type is humid & value > humid_threshold
            wso -> esp : request display "vmc high speed"
            esp -> di : update display content
        end
    end
end




@@enduml